spring:
  ai:
    mcp:
      server:
        type: sync
        sse-endpoint: /sse
        name: mcp-server
        enabled: true
  application:
    name: aurora-mcp-server

ai:
  dashscope:
    api-key: sk-ff9aa8fa0ebe4dddbe3126694ac5bffc
    base-url: https://dashscope.aliyuncs.com/compatible-mode/v1


server:
  port: 8081